name: .NET build pipeline

# Triggers
on:
  push:
    branches:
      - main
      - draft
  pull_request:
    branches:
      - main
      - draft

#: Jobs to execute
jobs:
  ## Build DockerFileCopy image
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    ### Checkout repo
    - uses: actions/checkout@v3
      with: 
        fetch-depth: 0
    ### Generate version number
    - name: Get version
      id: get_version
      uses: kingtechnl/githubactions/gitversion@main

    ### Build docusaurus site
    - name: Build docusaurus site
      uses: kingtechnl/githubactions/docusaurus/build@feature/docusaurus
      with:
        sourceDir: '${{ github.workspace }}'
        targetDir: '${{ github.workspace }}/publish'
        siteName: 'KingTech Labs'
        #baseUrl: '/'
        url: 'http://labs.kingtech.nl/'
        #url: 'https://kingtechlabs.github.io/KingTech.Labs/'

    ### Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: kingtechnl/githubactions/deploy-pages@feature/docusaurus
      with:
        sourceDir: '${{ github.workspace }}/publish'
        targetBranch: 'gh-pages'
        commitMessage: "Deploy site github actions"
        userName: 'github-actions'
        userEmail: 'github-actions@users.noreply.github.com'
        token: ${{ secrets.DEPLOYMENT_TOKEN }}
    