name: .NET build pipeline

# Triggers
on:
  push:
    branches:
      - main
      - draft
  pull_request:
    branches:
      - main
      - draft

#: Jobs to execute
jobs:
  ## Build DockerFileCopy image
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    ### Checkout repo
    - uses: actions/checkout@v3
      with: 
        fetch-depth: 0

    ### Build docusaurus site
    - name: Build docusaurus site
      uses: kingtechnl/githubactions/docusaurus-build@main
      with:
        targetDir: '${{ github.workspace }}/_publish'
        siteName: 'KingTech Labs'
        baseUrl: '/'
        brand: 'KingTech'
        logo: 'https://www.gravatar.com/avatar/1c367716e9c649121b5b877ad2f1b72f'
        favicon: 'https://www.gravatar.com/avatar/1c367716e9c649121b5b877ad2f1b72f'
        packages: 'react-image-gallery@2.1.1'
        NavbarFromRootDir: 'true'
        #customCss: './static/custom-css.css'
        kingtechActionsBranch: 'feature/fix-docusaurus-navbar-subfolders-not-showing'

    ### Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: kingtechnl/githubactions/deploy-pages@main
      with:
        sourceDir: '${{ github.workspace }}/_publish'
        targetBranch: 'gh-pages'
        commitMessage: "Deploy site github actions"
        userName: 'github-actions'
        userEmail: 'github-actions@users.noreply.github.com'
        token: ${{ secrets.DEPLOYMENT_TOKEN }}
        url: 'labs.kingtech.nl'